language: node_js
node_js:
  - '12'
cache: 
  directories:
    - node_modules
    - ~/.npm

stages:
  - production
  - staging
  - name: test
    if: type = push AND branch = staging

jobs:
  include:
    - stage: test
      script: 
        - echo 'Dentro del Estado de pruebas'
        - echo 'Ejecuto la instalación de los componentes'
        - npm install
        - echo 'Ya instale ahora hago las pruebas'
        - echo type
    - stage: staging
      script:
        - npm run build
      deploy: 
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: 'sec.anjrot.cl'
        skip_cleanup: true
        local_dir: dist/
        commit_message: 'Deploy del proyecto'
        on:
          branch: staging