language: node_js
node_js:
  - '12'
cache: 
  directories:
    - node_modules
    - ~/.npm

before_script:
  - npm install

jobs:
  include:        
    - stage: staging
      script:
        - echo 'Aquí debería ejecutar npm run test'
        - echo "si todos los tests pasan seguimos adelante"
      after_success:
        - npm run build
      branches:
        - staging        
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: 'prueba-deploy'
        skip_cleanup: true
        local_dir: dist/
        commit_message: 'Deploy del proyecto'

  