language: node_js
node_js:
  - '12'
cache: 
  directories:
    - node_modules
    - ~/.npm

stages:
  - name: staging
    # require the type to be a PR
    if: type = push AND branch = staging
  - name: production
    # require the type to be push to master
    if: type = push AND branch = master

before_script:
  - npm install


jobs:
  include:        
    - stage: staging
      script:
        - echo 'Aquí debería ejecutar npm run test'
        - echo "si todos los tests pasan seguimos adelante"
      after_success:
        - npm run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        skip_cleanup: true
        keep_history: true
        bucket: 'prueba-deploy'
        local_dir: dist/
        on:
          branch: staging

    - stage: production
      script:
        - echo 'Aquí debería ejecutar npm run test'
        - echo "si todos los tests pasan seguimos adelante"
      after_success:
        - npm run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        skip_cleanup: true
        keep_history: true
        bucket: 'sec.anjrot.cl'
        local_dir: dist/
        on:
          branch: master

  